/*
 * Automatically generated C config: don't edit
 * Tue Aug 10 19:52:12 2010
 */

/* OSes supported */
#define ATL_WIN32 		0
#define ATL_NU 			1
#define ATL_MTK 		2
#define ATL_LINUX 		3
#define ATL_LINUXKERNEL 	4
/* the current OS */
//#define ATL_PLATFORM ATL_LINUXKERNEL


/* Logs options */
#define ATL_LOGS_NOTHING          0
#define ATL_LOGS_WARN             1
#define ATL_LOGS_WARN_INFO        2
#define ATL_LOGS_WARN_INFO_DBG    3
#define ATL_LOGS_WARN_INFO_DBG_FN 4
#define ATL_LOGS_ALL              5

#define ATL_LOG_VERBOSITY_LEVEL ATL_LOGS_ALL

/* OS features supported */

#define CONFIG_ATL_THREAD_FEATURE 1
//#define CONFIG_ATL_THREAD_SUSPEND_CONTROL 1
//#define CONFIG_ATL_THREAD_STRICT_PRIORITY 1
#define CONFIG_ATL_SEMAPHORE_FEATURE 1
//#define CONFIG_ATL_SEMAPHORE_TIMEOUT 1
#define CONFIG_ATL_SLEEP_FEATURE 1
#define CONFIG_ATL_SLEEP_HI_RES 1
#define CONFIG_ATL_TIMER_FEATURE 1
//#define CONFIG_ATL_TIMER_PERIODIC 1 
#define CONFIG_ATL_MEMORY_FEATURE 1
//#define CONFIG_ATL_MEMORY_POOLS 1 
//#define CONFIG_ATL_MEMORY_DEBUG 1
//#define CONFIG_ATL_ASSERTION_SUPPORT 1
#define CONFIG_ATL_STRING_UTILS 1
#define CONFIG_ATL_MSG_QUEUE_FEATURE
//#define CONFIG_ATL_MSG_QUEUE_IPC_NAME
//#define CONFIG_ATL_MSG_QUEUE_TIMEOUT
//#define CONFIG_ATL_FILE_OPERATIONS_FEATURE
//#define CONFIG_ATL_FILE_OPERATIONS_STRING_API
//#define CONFIG_ATL_FILE_OPERATIONS_PATH_API
#define CONFIG_ATL_TIME_FEATURE
//#define CONFIG_ATL_EVENT_FEATURE
//#define CONFIG_ATL_EVENT_TIMEOUT
//#define CONFIG_ATL_SOCKET_FEATURE
//#define CONFIG_ATL_MATH_OPERATIONS_FEATURE
//#define CONFIG_ATL_EXTENDED_FILE_OPERATIONS
//#define CONFIG_ATL_EXTENDED_STRING_OPERATIONS
//#define CONFIG_ATL_EXTENDED_TIME_OPERATIONS
